# spring
spring:
  application:
    name: balance
  session:
    store-type: redis
  redis:
    port: 6379
    database: 1
    password: 123456
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/heshituina_balance_pidu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/