# spring
spring:

  # profiles
  profiles:
    active: dev
  # swagger
  swagger:
    enabled: true
    base-package: com.mozhumz.balance.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: error
    com.mozhumz.balance: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.mozhumz.balance.model.entity
  mapper-locations: classpath:mappers/*Mapper.xml

login:
  url: http://ec2-13-230-243-231.ap-northeast-1.compute.amazonaws.com/hstn/index.html

web:
  url: http://ec2-52-196-36-65.ap-northeast-1.compute.amazonaws.com/index.html

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


