# spring
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  # profiles
  profiles:
    active: dev
  # swagger
  swagger:
    enabled: true
    base-package: com.mozhumz.balance.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: error
    com.mozhumz.balance: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.mozhumz.balance.model.entity,com.mozhumz.balance.model.*
  mapper-locations: classpath:mappers/*Mapper.xml

login:
  url: http://localhost:8080/zuul/index.html

web:
  url: http://localhost:8080/balance/index.html

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


