# spring
spring:
  session:
    store-type: redis
  redis:
    port: 6379
    database: 1
    password: 123456
  # datasource
  datasource:
    # druid
    druid:
      url: jdbc:mysql://localhost:3306/balance_heshituina_pidu?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
# log
logging:
  level:
    com.mozhumz.balance.balance: info

server:
  port: 8080

